defmodule Storybook.DataEntry.ReactForm do
  use PhoenixStorybook.Story, :example
  import PhoenixDuskmoon.Component.DataEntry.ReactForm

  def doc,
    do:
      "Typed JSON forms with HEEX fields or generated JSON Schema controls, defaults, and server validation."

  @impl true
  def mount(_, _, socket),
    do: {:ok, assign(socket, submitted: nil, schema_submitted: nil)}

  @impl true
  def render(assigns) do
    ~H"""
    <div class="p-6 bg-surface text-on-surface">
      <h2 class="text-xl font-bold">React JSON Form</h2>
      <.dm_react_form
        id="react-profile"
        values={defaults()}
        phx-change="validate-profile"
        phx-submit="save-profile"
        phx-debounce="300"
        class="max-w-lg mt-4"
      >
        <div class="grid gap-4">
          <.dm_react_field name="name" type="text" label="Name" />
          <div class="grid grid-cols-2 gap-4">
            <.dm_react_field name="seats" type="number" label="Seats" />
            <.dm_react_field name="roles" type="multiselect" label="Roles" options={role_options()} />
          </div>
          <label class="flex gap-2 items-center"><input
            name="notes"
            class="input"
            value="Native HTML note"
          /> Notes</label>
          <button type="submit" class="btn btn-primary">Save</button>
          <button type="reset" class="btn btn-outline">Reset</button>
        </div>
      </.dm_react_form>
      <pre id="received-json" class="p-4 mt-4 bg-surface-container rounded">{if @submitted, do: Jason.encode!(@submitted, pretty: true), else: "No submission yet"}</pre>

      <h2 class="mt-8 text-xl font-bold">JSON Schema workspace</h2>
      <p class="mt-2 text-sm opacity-70">
        Schema defaults initialize a nested object, editable member array, numeric enum,
        and boolean. Try "taken" as the workspace name for a server validation error.
        Submit and Reset controls are generated by the upstream form.
      </p>
      <.dm_react_form
        id="storybook-schema-profile"
        schema={profile_schema()}
        phx-change="validate-schema-profile"
        phx-submit="save-schema-profile"
        phx-debounce="180"
        class="mt-4 max-w-2xl"
      />
      <button type="button" class="btn btn-outline mt-4" phx-click="load-schema-preset">
        Load schema preset
      </button>
      <pre id="received-schema-json" class="p-4 mt-4 bg-surface-container rounded">{if @schema_submitted, do: Jason.encode!(@schema_submitted, pretty: true), else: "No schema submission yet"}</pre>
    </div>
    """
  end

  @impl true
  def handle_event("validate-profile", %{"values" => values}, socket) do
    if values["name"] == "taken",
      do: {:reply, %{status: "error", errors: %{name: ["Already used"]}}, socket},
      else: {:reply, %{status: "ok"}, socket}
  end

  @impl true
  def handle_event("save-profile", %{"values" => values}, socket),
    do: {:reply, %{status: "ok", message: "Saved"}, assign(socket, :submitted, values)}

  def handle_event("validate-schema-profile", %{"values" => values}, socket),
    do: {:reply, schema_reply(values), socket}

  def handle_event("save-schema-profile", %{"values" => values}, socket) do
    case schema_reply(values) do
      %{status: "ok"} ->
        {:reply, %{status: "ok", message: "Saved"}, assign(socket, :schema_submitted, values)}

      reply ->
        {:reply, reply, socket}
    end
  end

  def handle_event("load-schema-preset", _, socket) do
    values = %{
      "profile" => %{
        "name" => "Platform team",
        "plan" => 3,
        "seats" => 12,
        "notifications" => false
      },
      "members" => [%{"email" => "team@example.test"}, %{"email" => "ops@example.test"}]
    }

    {:noreply,
     push_event(socket, "dm:form:reset", %{id: "storybook-schema-profile", values: values})}
  end

  defp schema_reply(values) do
    if get_in(values, ["profile", "name"]) == "taken",
      do: %{status: "error", errors: %{"/profile/name" => "Workspace name is already reserved"}},
      else: %{status: "ok"}
  end

  defp profile_schema do
    %{
      "type" => "object",
      "required" => ["profile", "members"],
      "properties" => %{
        "profile" => %{
          "type" => "object",
          "title" => "Workspace",
          "required" => ["name", "plan", "seats"],
          "properties" => %{
            "name" => %{
              "type" => "string",
              "title" => "Workspace name",
              "minLength" => 1,
              "default" => "Moonlight team"
            },
            "plan" => %{
              "type" => "integer",
              "title" => "Plan",
              "enum" => [1, 2, 3],
              "default" => 2,
              "x-widget" => "select",
              "x-options" => [
                %{"value" => 1, "label" => "Starter"},
                %{"value" => 2, "label" => "Team"},
                %{"value" => 3, "label" => "Enterprise"}
              ]
            },
            "seats" => %{"type" => "integer", "title" => "Seats", "minimum" => 1, "default" => 3},
            "notifications" => %{
              "type" => "boolean",
              "title" => "Email notifications",
              "default" => true
            }
          }
        },
        "members" => %{
          "type" => "array",
          "title" => "Members",
          "minItems" => 1,
          "default" => [%{"email" => "ada@example.test"}],
          "items" => %{
            "type" => "object",
            "required" => ["email"],
            "properties" => %{
              "email" => %{"type" => "string", "title" => "Member email", "format" => "email"}
            }
          }
        }
      }
    }
  end

  defp defaults, do: %{name: "Ada", seats: 2, roles: ["reader"]}

  defp role_options,
    do: [
      %{value: "reader", label: "Reader"},
      %{value: "editor", label: "Editor"},
      %{value: "admin", label: "Admin"}
    ]
end
