#ifndef _WAMR_ZIG_H_
#define _WAMR_ZIG_H_

#define WASM_ENABLE_INTERP 1
#define WASM_ENABLE_AOT 0
#define WASM_ENABLE_FAST_INTERP 0
#define WASM_ENABLE_LIBC_BUILTIN 0
#define WASM_ENABLE_LIBC_WASI 0
#define WASM_ENABLE_MULTI_MODULE 0
#define WASM_ENABLE_BULK_MEMORY 1
#define WASM_ENABLE_REF_TYPES 1
#define WASM_ENABLE_SIMD 0
#define WASM_ENABLE_TAIL_CALL 1
#define WASM_ENABLE_MEMORY64 0
#define WASM_ENABLE_GC 0
#define WASM_ENABLE_THREAD_MGR 0
#define WASM_ENABLE_SHARED_MEMORY 0
#define WASM_ENABLE_EXCE_HANDLING 0
#define WASM_ENABLE_MINI_LOADER 0
#define WASM_ENABLE_WAMR_COMPILER 0
#define WASM_ENABLE_JIT 0
#define WASM_ENABLE_FAST_JIT 0
#define WASM_ENABLE_DEBUG_INTERP 0
#define WASM_ENABLE_INSTRUCTION_METERING 1
#define WASM_ENABLE_DUMP_CALL_STACK 0
#define WASM_ENABLE_PERF_PROFILING 0
#define WASM_ENABLE_LOAD_CUSTOM_SECTION 0
#define WASM_ENABLE_CUSTOM_NAME_SECTION 1
#define WASM_ENABLE_GLOBAL_HEAP_POOL 0
#define WASM_ENABLE_SPEC_TEST 0
#define WASM_ENABLE_LABELS_AS_VALUES 1
#define WASM_ENABLE_WASM_CACHE 0
#define WASM_ENABLE_STRINGREF 0
#define WASM_MEM_ALLOC_WITH_SYSTEM_ALLOCATOR 1
#define WASM_RUNTIME_API_EXTERN
#define BH_MALLOC malloc
#define BH_FREE free

#include "wamr_bridge.h"

#endif /* _WAMR_ZIG_H_ */
