defmodule DuskmoonBundler.Config.Build do
  @moduledoc "Normalized production build configuration."

  defstruct entry: DuskmoonBundler.Paths.entry(),
            outdir: DuskmoonBundler.Paths.static(),
            public_dir: false,
            target: :es2020,
            minify: true,
            sourcemap: true,
            hash: true,
            code_splitting: true,
            tree_shaking: true,
            format: :iife,
            mode: :production,
            env_prefix: "DUSKMOON_BUNDLER_",
            asset_url_prefix: DuskmoonBundler.Paths.prefix(),
            external: [],
            aliases: %{},
            chunks: %{},
            plugins: [],
            resolve_dirs: [],
            vendor_source: [],
            root: DuskmoonBundler.Paths.assets(),
            sources: ["**/*.{js,ts,jsx,tsx,vue}"],
            ignore: ["vendor/**" | DuskmoonBundler.Paths.ignored_globs()],
            import_source: nil,
            vapor: false,
            custom_renderer: false,
            module_types: %{}
end
