repositoryUrl: https://github.com/duskmoon-dev/phoenix-duskmoon-ui.git
branches:
  - +([0-9])?(.{+([0-9]),x}).x
  - {name: '2.x', range: '2.x.x'}
  - main
  - next
  - next-major
  - {name: 'beta', prerelease: true}
  - {name: 'alpha', prerelease: true}
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - - "@semantic-release/exec"
    - "prepareCmd" : |
        echo ${nextRelease.version};
        sed -i 's%@version "[^"]\+"%@version "${nextRelease.version}"%' mix.exs;
        sed -i 's%"version": "[^"]\+"%"version": "${nextRelease.version}"%' package.json;
        sed -i 's%@version "[^"]\+"%@version "${nextRelease.version}"%' ../../mix.exs;
        mix prepublish;
      "publishCmd" : |
        echo publish phoenix_duskmoon ${nextRelease.version};
        mix hex.publish --yes;
        if test -z "${nextRelease.channel}";
        then
          npm publish;
        else
          npm publish --tag "${nextRelease.channel}";
        fi
        echo "new_release_version=${nextRelease.version}" >> "$GITHUB_OUTPUT";
        echo "new_release_channel=${nextRelease.channel}" >> "$GITHUB_OUTPUT";
  - - "@semantic-release/git"
    - "assets":
        - "CHANGELOG.md"
        - "mix.exs"
        - "package.json"
        - "../../mix.exs"
      "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
  - "@semantic-release/github"
