name: Tests

on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Run tests (Elixir ${{matrix.elixir}}, OTP ${{matrix.otp}})

    strategy:
      matrix:
        include:
          - elixir: 1.16
            otp: 26
          - elixir: 1.18
            otp: 27

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Elixir
      uses: erlef/setup-elixir@v1
      with:
        elixir-version: ${{ matrix.elixir }}
        otp-version: ${{ matrix.otp }}

    - name: Restore deps and _build cache
      uses: actions/cache@v3
      with:
        path: |
          deps
          _build
        key: deps-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          deps-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}

    - name: Install dependencies
      run: mix deps.get --only test
      env:
        MIX_ENV: test

    - name: Check source code format
      run: mix format --check-formatted
      env:
        MIX_ENV: test

    - name: Remove compiled application files
      run: mix clean

    - name: Compile & lint dependencies
      run: mix compile --warnings-as-errors
      env:
        MIX_ENV: test

    - name: Run tests
      run: mix test
      env:
        MIX_ENV: test
