name: Tests

on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Run tests (Elixir ${{matrix.elixir}}, OTP ${{matrix.otp}})

    strategy:
      matrix:
        include:
          - elixir: 1.18
            otp: 28
          - elixir: 1.18
            otp: 27

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Set up Elixir
      uses: erlef/setup-elixir@v1
      with:
        elixir-version: ${{ matrix.elixir }}
        otp-version: ${{ matrix.otp }}

    - name: Restore deps and _build cache
      uses: actions/cache@v3
      with:
        path: |
          deps
          _build
        key: deps-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          deps-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}

    - name: Install dependencies
      run: mix deps.get --only test
      env:
        MIX_ENV: test

    - name: Check source code format
      run: mix format --check-formatted
      env:
        MIX_ENV: test

    - name: Remove compiled application files
      run: mix clean

    - name: Compile & lint dependencies
      run: |
        # Try to compile with warnings as errors, but allow known warnings
        if ! mix compile --warnings-as-errors; then
          echo "Compilation with warnings-as-errors failed, checking for known warnings..."
          # Get all warnings
          warnings=$(mix compile 2>&1 | grep -i warning || true)
          echo "Warnings detected:"
          echo "$warnings"
          
          # Check if all warnings are known and acceptable
          if echo "$warnings" | grep -v "this clause cannot match because a previous clause at line.*matches the same pattern as this clause" | \
             grep -v "Can't resolve css_path: can't read" | \
             grep -v "Can't resolve js_path: can't read" | \
             grep -q .; then
            echo "Unknown compilation warnings found, failing build."
            mix compile
            exit 1
          else
            echo "Only known acceptable warnings detected, continuing..."
          fi
        fi
      env:
        MIX_ENV: test

    - name: Run tests
      run: mix test
      env:
        MIX_ENV: test
